spring:
  application:
    name: Popcorn Time

logging:
  level:
    org.springframework: WARN
    com.github.yoep.popcorn: INFO

popcorn:
  providers:
    movies:
      url: https://tv-v2.api-fetch.website/movies
  genres:
    - all
    - action
    - adventure
    - animation
    - comedy
    - crime
    - disaster
    - documentary
    - drama
    - eastern
    - family
    - fan-film
    - fantasy
    - film-noir
    - history
    - holiday
    - horror
    - indie
    - music
    - mystery
    - none
    - road
    - romance
    - science-fiction
    - short
    - sports
    - sporting-event
    - suspense
    - thriller
    - tv-movie
    - war
    - western